export const businessPartnersConstants = {

	GET_BPARTNERS_REQUEST: "GET_BPARTNERS_REQUEST",
	GET_BPARTNERS_SUCCESS: "GET_BPARTNERS_SUCCESS",
	GET_BPARTNERS_FAILURE: "GET_BPARTNERS_FAILURE",

	
	UPDATE_BPARTNER_DATA_MODAL_SHOW: "UPDATE_BPARTNER_DATA_MODAL_SHOW",
	UPDATE_BPARTNER_DATA_MODAL_HIDE: "UPDATE_BPARTNER_DATA_MODAL_HIDE",


	BUSINESS_PARTNER_UPDATE_SUCCESS: "BUSINESS_PARTNER_UPDATE_SUCCESS",
	BUSINESS_PARTNER_UPDATE_FAILURE: "BUSINESS_PARTNER_UPDATE_FAILURE",
	
	BUSINESS_PARTNER_DELETE_SUCCESS: "BUSINESS_PARTNER_DELETE_SUCCESS",
	BUSINESS_PARTNER_DELETE_FAILURE: "BUSINESS_PARTNER_DELETE_FAILURE",

	
	BUSINESS_PARTNER_SUCCESS_FAILURE_HIDE: "BUSINESS_PARTNER_SUCCESS_FAILURE_HIDE",

};
